import '../js/components/refs'
import '../js/burger-menu';
import '../js/header'
import '../js/dark-light-theme';
import '../js/list-category';
import '../js/support';
import '../js/shopping';
import '../js/modal';
import '../js/auth';
import '../js/up-btn';
import '../js/footer';
