import '../js/components/refs';
import '../js/burger-menu';
import '../js/dark-light-theme';
import '../js/support';
import '../js/shopping';
import '../js/auth';
import '../js/up-btn';
import '../js/shopping-list'
import '../js/footer';
